############################################################
# Research Dataset Pipeline (full indices set)
#
# Usage:
#   python scripts/pipelines/run_full_dataset.py --jquants \
#     --start-date 2020-09-06 --end-date 2025-09-06 \
#     --config configs/pipeline/research_full_indices.yaml
#
# CLI args still take precedence over this YAML.
############################################################

sector_cs:
  enable: true
  include_cols: ["rsi_14", "returns_10d"]

graph:
  enable: true
  window: 60
  threshold: 0.3
  max_k: 10
  cache_dir: "output/graph_cache"

indices:
  enable: true
  # Broad set covering market/segments, sector33, style/size, Topix-17, REIT
  codes:
    # Market & segments
    - "0000"  # TOPIX
    - "0500"  # Prime
    - "0501"  # Standard
    - "0502"  # Growth Market
    - "0503"  # JPX Prime150
    - "0070"  # Mothers/Growth250

    # Sector33 (0040–0060)
    - "0040"; - "0041"; - "0042"; - "0043"; - "0044"; - "0045"
    - "0046"; - "0047"; - "0048"; - "0049"; - "004A"; - "004B"
    - "004C"; - "004D"; - "004E"; - "004F"; - "0050"; - "0051"
    - "0052"; - "0053"; - "0054"; - "0055"; - "0056"; - "0057"
    - "0058"; - "0059"; - "005A"; - "005B"; - "005C"; - "005D"
    - "005E"; - "005F"; - "0060"

    # Style
    - "8100"; - "8200"; - "812C"; - "822C"; - "812D"; - "822D"

    # Size (TOPIX families)
    - "0028"; - "0029"; - "002A"; - "002B"; - "002C"; - "002D"; - "002E"; - "002F"

    # Topix‑17
    - "0080"; - "0081"; - "0082"; - "0083"; - "0084"; - "0085"
    - "0086"; - "0087"; - "0088"; - "0089"; - "008A"; - "008B"
    - "008C"; - "008D"; - "008E"; - "008F"; - "0090"

    # REIT
    - "0075"; - "8501"; - "8502"; - "8503"

  # Disable 2020-10-01 masking for range-derived features (default: false)
  disable_halt_mask: false

option_market:
  attach: false

