# ===========================================
# gogooku3-standalone Docker Compose Override
# ===========================================
# This file overrides docker-compose.yml with secure environment variables
# Copy .env.example to .env and fill in actual values
#
# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.override.yml up
#
# Security: This file should be committed to version control as it contains
# only variable references, not actual secrets.

version: '3.8'

services:
  # ========== Storage Services ==========

  # MinIO - S3-compatible object storage
  minio:
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?MINIO_ROOT_PASSWORD is required}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:-gogooku,feast,mlflow,dagster}

  # ClickHouse - OLAP database
  clickhouse:
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:?CLICKHOUSE_PASSWORD is required}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-gogooku3}

  # Redis - Cache and online feature store
  redis:
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?REDIS_PASSWORD is required}
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

  # ========== ML Platform Services ==========

  # MLflow - ML lifecycle management
  mlflow:
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://localhost:5000}

  # Dagster - Data orchestration
  dagster:
    environment:
      DAGSTER_HOME: ${DAGSTER_HOME:-/opt/dagster/dagster_home}
      DAGSTER_PG_PASSWORD: ${DAGSTER_PG_PASSWORD:-dagster}

  # ========== Application Services ==========

  # Main application (if containerized)
  # app:
  #   environment:
  #     JQUANTS_AUTH_EMAIL: ${JQUANTS_AUTH_EMAIL:?JQUANTS_AUTH_EMAIL is required}
  #     JQUANTS_AUTH_PASSWORD: ${JQUANTS_AUTH_PASSWORD:?JQUANTS_AUTH_PASSWORD is required}
  #     LOG_LEVEL: ${LOG_LEVEL:-INFO}
  #     PERF_POLARS_STREAM: ${PERF_POLARS_STREAM:-0}
  #     OBS_METRICS_ENABLED: ${OBS_METRICS_ENABLED:-0}
  #     DATA_QUALITY_ENABLED: ${DATA_QUALITY_ENABLED:-0}

  # ========== Optional: Development Overrides ==========

  # Uncomment for development with host networking
  # networks:
  #   default:
  #     name: gogooku3-net
