defaults: []

pipeline:
  jquants: true
  # If null, uses today-5y .. today
  start_date: null
  end_date: null

  output_dir: output

  # Known inputs (optional)
  topix_parquet: null
  statements_parquet: null
  listed_info_parquet: null

  # Indices OHLC integration
  enable_indices: false
  indices_parquet: null
  indices_codes: null  # e.g., "0000,0040,0500,0501,..."

  # Futures
  enable_futures: true
  futures_parquet: null
  futures_categories: ["TOPIXF", "NK225F", "JN400F", "REITF"]
  futures_continuous: false

  # Advanced volatility
  enable_advanced_vol: false
  adv_vol_windows: [20, 60]

  # Basis spot indices (optional)
  nk225_parquet: null
  reit_parquet: null
  jpx400_parquet: null

  # Margin weekly
  enable_margin_weekly: false
  margin_weekly_parquet: null
  margin_weekly_lag: 3
  adv_window_days: 20

  # Margin daily
  enable_daily_margin: false
  daily_margin_parquet: null

  # Short selling
  enable_short_selling: false
  short_selling_parquet: null
  short_positions_parquet: null
  short_selling_z_window: 252

  # Earnings events
  enable_earnings_events: false
  earnings_announcements_parquet: null
  enable_pead_features: true

  # Sector short selling
  enable_sector_short_selling: false
  sector_short_selling_parquet: null
  enable_sector_short_z_scores: true
  sector_onehot33: false
  sector_series_mcap: auto
  sector_te_targets: null
  sector_series_levels: null
  sector_te_levels: null

  # Advanced features
  enable_advanced_features: false
  # Sector cross-sectional features
  enable_sector_cs: false
  sector_cs_cols: null
  # Graph features
  enable_graph_features: false
  graph_window: 60
  graph_threshold: 0.3
  graph_max_k: 4
  graph_cache_dir: null

  # Special days
  disable_halt_mask: false

  # Data quality checks
  quality_checks:
    enabled: true
    outlier_threshold: 3.0
    missing_threshold: 0.1
    save_report: true

  # Resilience
  resilience:
    enabled: true
    max_retries: 2
    checkpoint_enabled: true

  # Profiling
  profiling:
    enabled: true
    save_report: true

  # Incremental update
  update_mode: full   # full | incremental
  since_date: null    # YYYY-MM-DD (optional; if null, uses last metadata end+1)
