#!/bin/bash
# DEPRECATED: Moved to scripts/_archive on 2025-09-04
# Complete ATFT-GAT-FAN Training Script for gogooku3
# ATFT-GAT-FANの成果（Sharpe 0.849）を完全に再現する学習スクリプト

set -e

echo "========================================"
echo "Complete ATFT-GAT-FAN Training Script"
echo "Target Sharpe Ratio: 0.849"
echo "========================================"

# プロジェクトディレクトリに移動
cd /home/ubuntu/gogooku2/apps/gogooku3

# ログディレクトリ作成
mkdir -p logs
mkdir -p output/results

# タイムスタンプ
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOG_FILE="logs/complete_atft_training_${TIMESTAMP}.log"

echo "📝 Log file: $LOG_FILE"

# ===== ATFT-GAT-FAN成果再現設定 =====

# 1. 安定性設定（Sharpe 0.849を達成した設定）
export USE_T_NLL=1
export OUTPUT_NOISE_STD=0.02
export HEAD_NOISE_STD=0.05
export HEAD_NOISE_WARMUP_EPOCHS=5
export GAT_ALPHA_INIT=0.3
export GAT_ALPHA_MIN=0.1
export GAT_ALPHA_PENALTY=1e-3
export EDGE_DROPOUT_INPUT_P=0.1
export DEGENERACY_GUARD=1
export DEGENERACY_WARMUP_STEPS=1000
export DEGENERACY_CHECK_EVERY=200
export DEGENERACY_MIN_RATIO=0.05
export USE_AMP=1
export AMP_DTYPE=bf16

# 2. データ処理設定
export LABEL_CLIP_BPS_MAP="1:2000,2:2000,3:2000,5:2000,10:5000"
export NUM_WORKERS=16
export PREFETCH_FACTOR=4
export PIN_MEMORY=1
export PERSISTENT_WORKERS=1

# 3. 学習設定
export BATCH_SIZE=2048
export LEARNING_RATE=5e-5
export MAX_EPOCHS=75
export PRECISION=bf16-mixed

# 4. ログ設定
export LOG_LEVEL=INFO
export LOG_TZ=Asia/Tokyo

echo ""
echo "🎯 Target Configuration:"
echo "  Expected Sharpe Ratio: 0.849"
echo "  Model Parameters: 5,611,803"
echo "  Input Dimension: 8"
echo "  Sequence Length: 20"
echo "  Prediction Horizons: [1, 2, 3, 5, 10]"
echo ""
echo "🔧 Stability Settings:"
echo "  USE_T_NLL=$USE_T_NLL"
echo "  OUTPUT_NOISE_STD=$OUTPUT_NOISE_STD"
echo "  HEAD_NOISE_STD=$HEAD_NOISE_STD"
echo "  GAT_ALPHA_INIT=$GAT_ALPHA_INIT"
echo "  DEGENERACY_GUARD=$DEGENERACY_GUARD"
echo ""
echo "📊 Training Settings:"
echo "  BATCH_SIZE=$BATCH_SIZE"
echo "  LEARNING_RATE=$LEARNING_RATE"
echo "  MAX_EPOCHS=$MAX_EPOCHS"
echo "  PRECISION=$PRECISION"
echo ""

# ===== 完全な学習パイプライン実行 =====

echo "🚀 Starting Complete ATFT-GAT-FAN Training Pipeline..."

# 1. 統合学習パイプライン実行
echo "📋 Step 1: Running integrated training pipeline..."
python scripts/integrated_ml_training_pipeline.py 2>&1 | tee -a "$LOG_FILE"

if [ $? -eq 0 ]; then
    echo "✅ Step 1 completed successfully"
else
    echo "❌ Step 1 failed"
    exit 1
fi

# 2. 学習結果の検証
echo "🔍 Step 2: Validating training results..."
python scripts/train_atft_wrapper.py --validate_only 2>&1 | tee -a "$LOG_FILE"

if [ $? -eq 0 ]; then
    echo "✅ Step 2 completed successfully"
else
    echo "❌ Step 2 failed"
    exit 1
fi

# 3. 推論システムのテスト
echo "🧪 Step 3: Testing inference system..."
python test_atft_integration.py 2>&1 | tee -a "$LOG_FILE"

if [ $? -eq 0 ]; then
    echo "✅ Step 3 completed successfully"
else
    echo "❌ Step 3 failed"
    exit 1
fi

# 4. 成果レポート生成
echo "📊 Step 4: Generating results report..."

# チェックポイント情報の取得
CHECKPOINT_DIR="/home/ubuntu/gogooku2/apps/ATFT-GAT-FAN/models/checkpoints"
LATEST_CHECKPOINT=$(ls -t "$CHECKPOINT_DIR"/*.pt 2>/dev/null | head -1)

if [ -n "$LATEST_CHECKPOINT" ]; then
    CHECKPOINT_SIZE=$(du -h "$LATEST_CHECKPOINT" | cut -f1)
    echo "📁 Latest checkpoint: $LATEST_CHECKPOINT ($CHECKPOINT_SIZE)"
else
    echo "⚠️ No checkpoints found"
fi

# 結果レポート作成
REPORT_FILE="output/results/complete_training_report_${TIMESTAMP}.md"

cat > "$REPORT_FILE" << EOF
# Complete ATFT-GAT-FAN Training Report

## Training Summary
- **Timestamp**: $(date)
- **Target Sharpe Ratio**: 0.849
- **Status**: ✅ Completed Successfully

## Configuration
### ATFT-GAT-FAN Settings
- Expected Sharpe Ratio: 0.849
- Model Parameters: 5,611,803
- Input Dimension: 8
- Sequence Length: 20
- Prediction Horizons: [1, 2, 3, 5, 10]

### Stability Settings
- USE_T_NLL: $USE_T_NLL
- OUTPUT_NOISE_STD: $OUTPUT_NOISE_STD
- HEAD_NOISE_STD: $HEAD_NOISE_STD
- GAT_ALPHA_INIT: $GAT_ALPHA_INIT
- DEGENERACY_GUARD: $DEGENERACY_GUARD

### Training Settings
- Batch Size: $BATCH_SIZE
- Learning Rate: $LEARNING_RATE
- Max Epochs: $MAX_EPOCHS
- Precision: $PRECISION

## Results
- **Checkpoint**: $LATEST_CHECKPOINT
- **Checkpoint Size**: $CHECKPOINT_SIZE
- **Log File**: $LOG_FILE

## Integration Tests
- ✅ Model Loading
- ✅ Feature Conversion
- ✅ Inference
- ✅ End-to-End Pipeline

## Next Steps
1. Verify Sharpe ratio achievement
2. Run backtesting
3. Deploy to production

---
*Generated by Complete ATFT-GAT-FAN Training Script*
EOF

echo "📄 Results report saved: $REPORT_FILE"

# ===== 完了メッセージ =====

echo ""
echo "========================================"
echo "🎉 Complete ATFT-GAT-FAN Training Completed!"
echo "========================================"
echo ""
echo "📊 Results:"
echo "  ✅ Training Pipeline: Success"
echo "  ✅ Model Validation: Success"
echo "  ✅ Inference Tests: Success"
echo "  📁 Checkpoint: $LATEST_CHECKPOINT"
echo "  📄 Report: $REPORT_FILE"
echo "  📝 Log: $LOG_FILE"
echo ""
echo "🎯 Next Steps:"
echo "  1. Check Sharpe ratio in logs"
echo "  2. Run backtesting if needed"
echo "  3. Deploy to production"
echo ""
echo "========================================"

# ログファイルの場所を表示
echo "📝 Full training log: $LOG_FILE"
echo "📄 Results report: $REPORT_FILE"
