data:
  graph_builder:
    cache_dir: graph_cache
    ewm_halflife: 30
    k: 20
    edge_threshold: 0.3
    log_mktcap_col: log_mktcap
    lookback: 60
    method: ewm_demean
    min_obs: 40
    use_in_training: false  # OPTIMIZATION: Disable graph rebuild during validation (GPU bottleneck fix)
    return_cols:
    - return_1d
    - feat_ret_1d
    returns_channel_index: 0
    sector_col: sector33
    shrinkage_gamma: 0.1
    size_tau: 1.0
    source_glob: ${data.source.data_dir}/train/*.parquet
    symmetric: true
debug:
  detect_anomaly: false
  enabled: false
  fast_dev_run: 10
  profiler: false
defaults:
- _self_
- data: jpx_large_scale
- model: atft_gat_fan
- train: production
- hardware: default
- override hydra/hydra_logging: default
- override hydra/job_logging: default
hydra:
  job:
    chdir: false
    name: ATFT-GAT-FAN
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
improvements:
  auto_recover_oom: true
  compile_model: false
  edge_dropout_p: 0.0
  ema_decay: 0.995          # 最適化: 0.995
  emergency_checkpoint: false
  enable_tensorboard: true
  enable_wandb: true
  freq_dropout_max_width: 0.2
  freq_dropout_min_width: 0.05
  freq_dropout_p: 0.2         # 最適化: 0.2
  gat_alpha_min: 0.05
  gat_temperature: 0.8        # 最適化: 0.8
  huber_delta: 0.01           # 最適化: 0.01
  huber_loss: true
  log_grad_norm: false
  memory_map: false
  multi_horizon_weights:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  online_normalization: true
  output_head_small_init: true
  use_ema: true
logging:
  level: INFO
mode: train
paths:
  data: data
  logs: logs
  models: models
  root: .
project:
  deterministic: true
  name: ATFT-GAT-FAN
  seed: 42

normalization:
  online_normalization:
    enabled: true
    max_samples: 250000
    random_state: 42
  cross_sectional:
    enabled: false
