feature_categories:
  basic:
  - TurnoverValue
  - Volume
  - Volume
  - alpha_1d
  - beta_60d_raw
  - close
  - high
  - low
  - open
  - shares_outstanding
  - stmt_roa
  - stmt_roe
  - volume
  technical:
  - Low
  - Low
  - adx_14
  - atr_14
  - bb_width
  - macd
  - macd
  - macd_signal
  - rsi_14
  - rsi_2
  - stoch_k
  ma_derived:
  - ema_10
  - ema_20
  - ema_5
  - ema_60
  - mkt_ema20_slope_3
  - sma_10
  - sma_120
  - sma_20
  - sma_5
  - sma_60
  returns:
  - feat_ret_1d
  - log_returns_1d
  - log_returns_20d
  - log_returns_5d
  - returns_10d
  - returns_1d
  - returns_20d
  - returns_20d
  - returns_5d
  - returns_5d
  - returns_60d
  - returns_60d
  market:
  - Volume
  - Volume
  - Volume
  - Volume
  - Volume
  flows:
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  - Low
  statements:
  - Low
  - stmt_revenue_growth
  - stmt_revenue_growth
  additional:
  - ADV20_shares
  - IssueType
  - LocalCode
  - LongMarginTradeVolume
  - LongNegotiableMarginTradeVolume
  - LongStandardizedMarginTradeVolume
  - PublishedDate
  - Section
  - ShortMarginTradeVolume
  - ShortNegotiableMarginTradeVolume
  - ShortStandardizedMarginTradeVolume
  - activity_ratio
  - activity_z
  - alpha_5d
  - alpha_vs_regime
  - bb_bw
  - bb_pct_b
  - bb_position
  - beta_20d_raw
  - beta_60d
  - beta_rolling
  - beta_stability_60d
  - breadth_pos
  - close_to_high
  - close_to_low
  - days_since_flow
  - dollar_volume
  - effective_start
  - ema_200
  - feat_ret_10d
  - feat_ret_20d
  - feat_ret_5d
  - flow_activity_high
  - flow_activity_low
  - flow_activity_ratio
  - flow_activity_z
  - flow_breadth_pos
  - flow_days_since
  - flow_foreign_net_pos
  - flow_foreign_net_ratio
  - flow_foreign_net_z
  - flow_foreign_share
  - flow_impulse
  - flow_individual_net_ratio
  - flow_individual_net_z
  - flow_shock_flag
  - flow_smart_idx
  - flow_smart_mom4
  - flow_smart_pos
  - foreign_share_activity
  - foreigners_net_ratio
  - high_low_ratio
  - idio_vol_ratio
  - individuals_net_ratio
  - is_borrowable
  - is_flow_valid
  - is_margin_valid
  - is_section_fallback
  - is_stmt_valid
  - log_returns_10d
  - long_z52
  - ma_gap_20_60
  - ma_gap_5_20
  - macd_histogram
  - margin_credit_ratio
  - margin_d_long_to_adv20
  - margin_d_long_wow
  - margin_d_net_wow
  - margin_d_ratio_wow
  - margin_d_short_to_adv20
  - margin_d_short_wow
  - margin_days_since
  - margin_gross_mom4
  - margin_gross_z52
  - margin_imbalance
  - margin_impulse
  - margin_issue_type
  - margin_long_to_adv20
  - margin_long_tot
  - margin_neg_share_long
  - margin_neg_share_short
  - margin_net
  - margin_short_to_adv20
  - margin_short_tot
  - margin_std_share_long
  - margin_std_share_short
  - margin_total_gross
  - mkt_atr_14
  - mkt_bb_bw
  - mkt_bb_bw_z
  - mkt_bb_pct_b
  - mkt_big_move_flag
  - mkt_bull_200
  - mkt_dd_from_peak
  - mkt_dd_from_peak_z
  - mkt_dev_20
  - mkt_ema_20
  - mkt_ema_200
  - mkt_ema_5
  - mkt_ema_60
  - mkt_gap_5_20
  - mkt_high_vol
  - mkt_natr_14
  - mkt_ret_10d
  - mkt_ret_1d
  - mkt_ret_1d_z
  - mkt_ret_20d
  - mkt_ret_5d
  - mkt_squeeze
  - mkt_trend_up
  - mkt_vol_20d
  - mkt_vol_20d_z
  - price_to_sma20
  - price_to_sma5
  - price_to_sma60
  - ratio_z52
  - realized_volatility
  - rel_strength_5d
  - returns_120d
  - row_idx
  - rsi_delta
  - section_norm
  - short_z52
  - smart_money_idx
  - smart_money_mom4
  - stmt_change_in_est
  - stmt_days_since_statement
  - stmt_imp_statement
  - stmt_nc_flag
  - stmt_npm
  - stmt_opm
  - stmt_profit_margin
  - stmt_progress_np
  - stmt_progress_op
  - stmt_rev_div_fore
  - stmt_rev_fore_eps
  - stmt_rev_fore_np
  - stmt_rev_fore_op
  - stmt_yoy_np
  - stmt_yoy_op
  - stmt_yoy_sales
  - target_10d_binary
  - target_1d_binary
  - target_20d_binary
  - target_5d_binary
  - trend_align_mkt
  - volatility_10d
  - volatility_20d
  - volatility_5d
  - volatility_60d
  - volume_ma_20
  - volume_ma_5
  - volume_ratio_20
  - volume_ratio_5
expected_counts:
  basic: 13
  technical: 11
  ma_derived: 10
  returns: 12
  market: 5
  flows: 17
  statements: 3
  additional: 154
  total: 193
