global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'gogooku3-monitor'

scrape_configs:
  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'gogooku3-host'

  # Dagster metrics
  - job_name: 'dagster'
    static_configs:
      - targets: ['dagster-webserver:3001']
        labels:
          service: 'dagster'
    metrics_path: '/metrics'

  # MLflow metrics
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
        labels:
          service: 'mlflow'
    metrics_path: '/metrics'

  # Feast metrics
  - job_name: 'feast'
    static_configs:
      - targets: ['feast-server:6566']
        labels:
          service: 'feast'
    metrics_path: '/metrics'

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
        labels:
          service: 'clickhouse'
    metrics_path: '/metrics'

  # Redis metrics (via redis_exporter if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
        labels:
          service: 'minio'
    metrics_path: '/minio/v2/metrics/cluster'

  # PostgreSQL metrics (via postgres_exporter if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files
rule_files:
  - '/etc/prometheus/rules/*.yml'
