# Join settings configuration

interval_join:
  strategy: backward  # as-of join strategy
  allow_exact_matches: true
  
asof_join:
  financial:
    t_plus_1: true
    cutoff_time: "15:00:00"
    handle_duplicates: latest  # latest | first | aggregate
    
  flow:
    t_plus_1: true
    expand_intervals: true
    fill_forward_days: 30  # Max days to carry forward flow data
    
cross_features:
  beta:
    window: 60
    min_observations: 30
    ridge_lambda: 1.0e-8
    
  correlation:
    window: 60
    min_observations: 30
    
  relative_strength:
    horizons: [5, 10, 20]
    
  volatility_ratio:
    individual_window: 20
    market_window: 20
    
  stability:
    window: 20
    metric: std  # std | mad
    
business_calendar:
  exclude_weekends: true
  exclude_holidays: true
  jpx_specific:
    year_end_closure: [12-31, 01-01, 01-02, 01-03]
    
data_validation:
  check_overlaps: true
  check_gaps: true
  max_gap_days: 5
  warn_on_duplicates: true