name: safe_production

# =============================================================================
# BATCH PROCESSING SAFETY & FINANCIAL ML BEST PRACTICES
# =============================================================================
# This configuration implements comprehensive safety measures to prevent data
# leakage in financial time series prediction following the checklist:
# - P0: Data leakage prevention (Walk-Forward + embargo + cross-sectional Z-score)
# - P1: Sampler/collate design (Date-Bucketed + enhanced graph processing)
# - P1: Financial metrics (Daily IC, RankIC, Decile analysis)
# - P2: Quality improvements (Curriculum learning + peer features)

# Walk-Forward Cross-Validation with Embargo Period
walk_forward:
  enabled: true
  n_splits: 5
  embargo_days: 20  # 20-day embargo period to prevent leakage
  validation_ratio: 0.2
  test_ratio: 0.2
  min_train_days: 180
  purge_overlapping: true
  verbose: true

# Date-Bucketed Sampler (Same-day batches for statistical consistency)
# Note: WalkForwardDateBucketSampler integration pending
sampler:
  type: standard
  batch_size: 1024
  shuffle: true
  seed: 42
  drop_last: false

# Cross-sectional Z-score Normalization (Daily statistics only)
# Implemented component - ready for integration
normalization:
  type: CrossSectionalNormalizer
  enabled: true
  min_stocks_per_day: 10
  fillna_method: forward_fill
  outlier_clip_percentiles: [0.01, 0.99]
  store_daily_stats: true
  use_daily_stats_only: true
  fallback_to_global: true
  verbose: true

# Enhanced Collate Function with Graph Snapshots
# Implemented component - ready for integration
collate_fn:
  type: enhanced_financial_collate_fn
  include_graph: true
  include_peer_features: true
  graph_cache_dir: ./cache/graphs
  validate_same_date: true
  graph_settings:
    type: dynamic_knn
    k_neighbors: 10
    exclude_self: true
    symmetric: true
    min_nodes_for_graph: 10

# Peer Feature Extraction (Neighbor statistics)
peer_features:
  enabled: true
  type: PeerFeatureExtractor
  k_neighbors: 10
  correlation_window: 60
  min_correlation_periods: 20
  method: mixed  # sector + correlation
  cache_correlations: true
  feature_types:
    - peer_mean
    - peer_std
    - peer_diff
    - peer_rank_percentile

# Curriculum Learning (Progressive complexity)
curriculum_learning:
  enabled: true
  type: CurriculumScheduler
  max_epochs: 100
  base_sequence_length: 40
  target_sequence_length: 60
  base_horizons: [1]
  target_horizons: [1, 2, 3, 5, 10, 20]
  enable_difficulty_sampling: true
  # 4 phases: simple_baseline -> sequence_extension -> multi_horizon -> full_complexity
  phase_transitions: [25, 50, 75]  # Epoch percentages for phase transitions

# Financial Metrics (Daily cross-sectional evaluation)
# Implemented component - ready for integration
financial_metrics:
  enabled: true
  type: FinancialMetrics
  min_stocks_per_day: 20
  decile_count: 10
  return_columns: [return_1d, return_5d, return_20d]
  compute_daily: true
  metrics:
    - information_coefficient
    - rank_ic
    - decile_analysis
    - hit_rate
    - sharpe_ratio

# Batch Configuration (Conservative for safety)
batch:
  train_batch_size: 1024
  val_batch_size: 2048
  test_batch_size: 2048
  num_workers: 4
  prefetch_factor: 2
  persistent_workers: true
  pin_memory: true
  gradient_accumulation_steps: 4

# Training Configuration (Stability-focused)
trainer:
  max_epochs: 100
  gradient_clip_val: 0.5
  gradient_clip_algorithm: norm
  accumulate_grad_batches: 4
  val_check_interval: 0.5
  check_val_every_n_epoch: 1
  log_every_n_steps: 25
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  detect_anomaly: true
  benchmark: false
  deterministic: true
  precision: 32

# Optimizer (Conservative settings)
optimizer:
  type: adamw
  lr: 0.0005                 # Lower learning rate for stability
  weight_decay: 0.02         # Higher weight decay for regularization
  betas: [0.9, 0.999]
  eps: 1e-8
  amsgrad: true              # More stable variant

# Learning Rate Scheduler
scheduler:
  type: ReduceLROnPlateau
  factor: 0.7
  patience: 7
  min_lr: 1e-6
  verbose: true
  threshold: 0.0001
  threshold_mode: rel

# Early Stopping (Conservative)
early_stopping:
  monitor: val/rank_ic
  mode: max
  patience: 15
  min_delta: 0.001
  verbose: true

# Loss Configuration (Multi-horizon)
loss:
  type: mse
  multi_horizon_weights: [1.0, 0.9, 0.8, 0.7, 0.6, 0.5]

# Model Checkpointing (Multi-metric)
checkpoint:
  monitor: val/rank_ic
  mode: max
  save_top_k: 5              # Keep more checkpoints for analysis
  save_last: true
  save_on_train_epoch_end: false
  filename: 'safe-prod-{epoch:03d}-{val_rank_ic:.4f}'
  # Save additional metrics in filename
  additional_filename_metrics:
    - val_information_coefficient
    - val_long_short_spread

# Enhanced Logging
logging:
  log_every_n_steps: 25
  log_grad_norm: true
  log_learning_rate: true
  log_financial_metrics: true
  aggregate_daily_metrics: true

# Validation Configuration (Enhanced for financial ML)
validation:
  # Daily cross-sectional evaluation
  per_date_metrics: true
  per_horizon_metrics: true
  # Outlier detection and handling
  outlier_detection: true
  outlier_threshold: 3.0
  # Financial-specific validation
  minimum_ic_threshold: 0.02     # Minimum acceptable IC
  maximum_turnover_rate: 2.0     # Portfolio turnover constraint
  validate_peer_features: true
  validate_normalization: true

# Data Safety Configuration
data_safety:
  # Correlation handling
  correlation_eps: 1e-8
  correlation_clamp: [-0.999, 0.999]
  nan_fill_value: 0.0
  # Time series safety
  verify_temporal_order: true
  check_future_leakage: true
  embargo_enforcement: true
  # Feature safety
  feature_stability_check: true
  cross_sectional_consistency: true
  # Graph safety
  graph_temporal_consistency: true
  peer_feature_leakage_check: true

# Hardware Optimizations (Conservative for stability)
hardware_optimizations:
  compile_model: false       # Disable JIT compilation for debugging
  channels_last: false       # Standard memory format
  tf32: false               # Disable for maximum precision
  cudnn_benchmark: false    # Disable for deterministic behavior
  gradient_checkpointing: false

# Memory Management
memory:
  empty_cache_frequency: 50  # Clear cache every 50 steps
  max_memory_usage: 0.9     # Limit GPU memory usage
  gradient_checkpointing: false
  # Cache management for safety components
  max_correlation_cache_size: 100  # Days to cache
  max_graph_cache_size: 50        # Days to cache
  clear_cache_between_folds: true

# Monitoring and Alerting
monitoring:
  # Financial metrics monitoring
  ic_trend_detection: true
  sharpe_degradation_alert: true
  turnover_spike_detection: true
  # System monitoring
  memory_usage_alert: true
  gradient_explosion_detection: true
  # Curriculum monitoring
  phase_transition_logging: true
  difficulty_progression_tracking: true

# Experiment Tracking
experiment:
  name: safe_production_run
  tags: [safe-batch, walk-forward, curriculum, financial-ml]
  description: "Production-safe training with comprehensive data leakage prevention"
  # Reproducibility
  seed: 42
  deterministic: true
  benchmark: false

# Post-training Analysis
post_training:
  # Financial performance analysis
  backtest_analysis: true
  portfolio_construction: true
  transaction_cost_analysis: false  # Disable for initial run
  # Model analysis
  feature_importance_analysis: true
  peer_feature_contribution: true
  curriculum_effectiveness_analysis: true
  # Safety verification
  leakage_detection_test: true
  temporal_consistency_check: true
  cross_sectional_validation: true

# Emergency Stops and Safeguards
safeguards:
  # Training safeguards
  max_ic_degradation: -0.05         # Stop if IC drops too much
  max_gradient_norm: 10.0           # Gradient explosion protection
  min_validation_samples: 1000      # Minimum samples for valid metrics
  # Financial safeguards
  max_portfolio_volatility: 0.3     # Risk management
  min_diversification_ratio: 0.5    # Concentration limits
  # System safeguards
  max_memory_usage_gb: 32          # Memory limit
  training_timeout_hours: 24       # Maximum training time