name: walk_forward
description: "Walk-Forward検証設定（embargo=20対応）"

# Walk-Forward設定
walk_forward:
  enabled: true
  n_splits: 5
  embargo_days: 20                     # 最大ホライズンに合わせる
  purge_days: 0                       # embargo内で処理
  min_train_days: 252                 # 最小1年の訓練期間
  min_test_days: 63                   # 最小3ヶ月のテスト期間
  test_size_days: null                # 自動計算
  overlap_check: true                 # 重複検証を有効

# 訓練設定
training:
  max_epochs: 50
  patience: 10                        # 早期停止の忍耐力
  
  # 学習率スケジューラ
  scheduler:
    type: "ReduceLROnPlateau"
    mode: "max"
    factor: 0.5
    patience: 5
    min_lr: 1e-6
  
  # 最適化設定
  optimizer:
    type: "AdamW"
    lr: 1e-3
    weight_decay: 5e-4
    betas: [0.9, 0.999]

# 早期停止設定
early_stopping:
  monitor: "val/rank_ic_5d"           # 実務寄りの5日RankIC
  mode: "max"
  patience: 10
  min_delta: 0.001
  restore_best_weights: true

# 損失関数設定
loss:
  type: "multi_horizon_mse"
  horizon_weights:                    # ホライズン別重み
    1: 1.0                           # 1日: 最重要
    5: 0.7                           # 5日: 重要
    10: 0.5                          # 10日: 中程度
    20: 0.5                          # 20日: 中程度

# 評価設定
evaluation:
  metrics:
    - "ic"                           # Information Coefficient
    - "rank_ic"                      # Rank IC (Spearman)
    - "decile_analysis"              # Decile分析
    - "mse"                          # Mean Squared Error
    - "mae"                          # Mean Absolute Error
  
  # 各ホライズンで評価
  evaluate_all_horizons: true
  
  # fold別に結果を保存
  save_fold_results: true
  fold_results_dir: "outputs/walk_forward_results"

# 正規化設定
normalization:
  # Cross-sectional Z-score
  cross_sectional:
    enabled: true
    method: "polars_v2"              # 高速Polars版
    cache_stats: true
    robust_clip: 5.0                 # ±5σクリップ
    
  # バッチ正規化禁止（データリーク防止）
  batch_norm:
    enabled: false
    warning: "BatchNorm disabled for data leakage prevention"

# データローダー設定  
data_loader:
  batch_size: 2048                    # 大きなバッチサイズ
  num_workers: 4
  pin_memory: true
  drop_last: false
  
  # Date-Bucketed Sampling
  sampler:
    type: "walk_forward_date_bucket_v2"
    max_batch_size: 2048
    min_nodes_per_day: 20
    shuffle: true
    seed: 42

# モデル設定調整
model_adjustments:
  # TFT設定
  tft:
    temporal:
      max_sequence_length: 60        # L=60対応
    
    # Variable Selection強化
    variable_selection:
      sparsity_coefficient: 0.01     # スパース性促進
      
  # GAT設定
  gat:
    layer_config:
      add_self_loops: false          # 自ループ無効
      
  # 適応正規化
  adaptive_normalization:
    fan:
      window_sizes: [5, 10, 20, 60]  # 系列長に合わせる

# ログ・保存設定
logging:
  # MLflow設定
  mlflow:
    enabled: true
    experiment_name: "walk_forward_gogooku3"
    track_fold_metrics: true
    
  # ログ内容
  log_items:
    - "fold_metrics"                 # fold別メトリクス
    - "variable_selection_weights"   # TFT変数選択重み
    - "attention_distributions"      # GAT attention分布
    - "daily_ic_series"             # 日次IC系列
    - "decile_performance"          # Decile分析結果

# 診断・デバッグ
diagnostics:
  # データリークチェック
  leak_detection:
    enabled: true
    check_overlap: true
    check_future_info: true
    
  # 統計チェック  
  stats_validation:
    check_normalization: true
    validate_distributions: true
    
  # パフォーマンス
  performance_profiling:
    enabled: false                   # 本番では無効
    memory_tracking: true

# 出力設定
outputs:
  # 結果保存
  save_predictions: true
  save_attention_weights: false      # 容量大のため通常無効
  
  # 可視化
  generate_plots: true
  plot_types:
    - "ic_time_series"               # IC時系列
    - "decile_returns"               # Decile収益
    - "prediction_distribution"      # 予測分布
    
  # レポート
  generate_report: true
  report_format: "html"

# リソース制限
resources:
  max_memory_gb: 16                  # 最大メモリ使用量
  gpu_memory_fraction: 0.8          # GPU メモリ使用率
  
# 実験設定
experiment:
  name_prefix: "wf_embargo20"        # 実験名プレフィックス
  tags:
    - "walk_forward"
    - "embargo_20"
    - "sequence_60"
    - "data_leak_safe"