name: default

# Hardware policy with environment-controlled fallbacks
# Use env to adapt between CI/CPU and production/GPU safely.
device: ${oc.env:DEVICE, cuda}
gpu_id: ${oc.env:GPU_ID, 0}

# DataLoader workers; default 0 for maximal compatibility in CI/smoke
num_workers: ${oc.env:NUM_WORKERS, 8}
pin_memory: ${oc.env:PIN_MEMORY, true}

# Mixed precision and tensor memory format
mixed_precision: ${oc.env:MIXED_PRECISION, true}
channels_last: ${oc.env:CHANNELS_LAST, true}

# A100-specific optimizations
a100_optimizations:
  tf32: true                 # Enable TF32 for A100
  cudnn_benchmark: true
  gradient_checkpointing: false

# Memory management
memory:
  max_memory_allocated: ${oc.env:MAX_MEMORY_ALLOCATED, 0.9}  # 90% of GPU memory
  memory_fraction: ${oc.env:MEMORY_FRACTION, 0.8}  # 80% of GPU memory
  allow_growth: ${oc.env:ALLOW_GROWTH, true}

# Performance tuning
performance:
  prefetch_factor: ${oc.env:PREFETCH_FACTOR, 4}
  persistent_workers: ${oc.env:PERSISTENT_WORKERS, true}
  drop_last: ${oc.env:DROP_LAST, false}
