_wandb:
    value:
        cli_version: 0.21.2
        e:
            exiv7u6gjp23x1izjxswizlaa70xld47:
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "311993479168"
                        used: "178744508416"
                email: wer.inc.jp@gmail.com
                executable: /usr/bin/python
                git:
                    commit: efdf5513758bec4a40ff4bb5a680175e89be5b52
                    remote: https://github.com/wer-inc/gogooku3.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6fa85c20-8593-3729-ad6e-4155943a1707
                host: client-instance-au9hc2cl
                memory:
                    total: "232209719296"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.10.12
                root: /home/ubuntu/gogooku3-standalone
                startedAt: "2025-08-30T00:06:28.991429Z"
                writerId: exiv7u6gjp23x1izjxswizlaa70xld47
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.21.2
            "12": 0.21.2
            "13": linux-x86_64
batch_size:
    value: 256
epochs:
    value: 3
learning_rate:
    value: 0.001
model:
    value: ATFT-GAT-FAN-demo
