version: 0_pruned

# Pruned configuration based on feature importance analysis (2025-10-29)
# Removed 25 features: 10 negative impact + 15 zero impact
# Expected improvement: P@K +7.4% (0.513 → 0.551)

data:
  parquet_path: output/ml_dataset_latest_full.parquet
  metadata_path: dataset_features_detail.json
  feature_groups_config: apex-ranker/configs/feature_groups.yaml
  feature_groups:
    - core50
  optional_groups: []
  use_plus30: true
  lookback: 180
  min_stocks_per_day: 80
  date_column: Date
  code_column: Code
  target_columns:
    1: target_1d
    5: target_5d
    10: target_10d
    20: target_20d

  # Features to exclude (25 total)
  exclude_features:
    # Bottom 10 features (negative impact)
    - rsi_2                        # -0.27%
    - flow_individual_net_ratio    # -0.30%
    - idio_vol_ratio               # -0.32%
    - stoch_k                      # -0.32%
    - ema_5                        # -0.57%
    - flow_foreign_net_z           # -0.58%
    - ema_200                      # -1.16%
    - ema_20                       # -1.39%
    - returns_20d                  # -1.78%
    - flow_breadth_pos             # -2.03% (worst feature)

    # Zero impact features (15 market features)
    - mkt_ret_1d
    - mkt_ret_5d
    - mkt_ret_10d
    - mkt_ret_20d
    - mkt_gap_5_20
    - mkt_vol_20d
    - mkt_bull_200
    - mkt_high_vol
    - mkt_ret_1d_z
    - mkt_dd_from_peak
    - mkt_bb_bw
    - mkt_bb_pct_b
    - mkt_ema20_slope_3
    - flow_impulse
    - flow_days_since

normalization:
  mode: cross_section_z
  clip_sigma: 5.0

train:
  horizons: [1, 5, 10, 20]
  epochs: 50
  lr: 0.0005
  weight_decay: 0.0001
  grad_clip: 0.5
  val_days: 120
  log_interval: 10
  amp: true
  device: auto
  num_workers: 0
  warmup_epochs: 3
  warmup_start_factor: 0.1
  early_stopping:
    patience: 3
    metric: 20d_pak
    min_delta: 0.0

model:
  d_model: 256
  depth: 4
  patch_len: 16
  stride: 8
  n_heads: 8
  dropout: 0.2

loss:
  listnet:
    weight: 1.0
    tau: 0.4
    topk: null
  ranknet:
    weight: 0.8
    neg_sample: 4096
  mse:
    weight: 0.05
