# J-Quants API Configuration
# APIエンドポイントとレート制限の設定

api_endpoints:
  base_url: "https://api.jquants.com/v1"
  
  # 主要エンドポイント
  trading_calendar: "/markets/trading_calendar"
  listed_info: "/listed/info"
  daily_quotes: "/prices/daily_quotes"
  topix: "/indices/topix"
  trades_spec: "/markets/trades_spec"
  statements: "/fins/statements"
  
# レート制限（有料プラン向け）
rate_limits:
  max_concurrent: 75  # 同時接続数
  requests_per_second: 100  # 秒間リクエスト数
  
  # エンドポイント別制限（req/min）
  endpoint_limits:
    trading_calendar: 60
    listed_info: 60
    daily_quotes: 300
    topix: 60
    trades_spec: 60
    statements: 60

# リトライ設定
retry_config:
  max_retries: 3
  backoff_factor: 2
  retry_on_status: [429, 500, 502, 503, 504]
  
# データ取得範囲
data_range:
  default_start: "2021-01-01"
  default_end: null  # null = 今日
  
# キャッシュ設定
cache:
  enabled: true
  ttl_hours: 24
  directory: "cache/"
  
  # エンドポイント別キャッシュ設定
  endpoint_cache:
    trading_calendar:
      enabled: true
      ttl_hours: 168  # 1週間
    listed_info:
      enabled: true
      ttl_hours: 24
    topix:
      enabled: false  # 価格データはキャッシュしない
    daily_quotes:
      enabled: false

# バッチ処理設定
batch_processing:
  chunk_size: 500  # 一度に処理する銘柄数（有料プラン向け）
  date_chunk_days: 30  # 日付チャンクサイズ
  daily_batch_size: 10  # 並列で処理する営業日数
  memory_limit_gb: 16.0  # メモリ上限（本番環境向け）
  
# ログ設定
logging:
  level: "INFO"
  show_progress: true
  log_api_calls: false  # デバッグ時のみtrue