_wandb:
    value:
        cli_version: 0.21.2
        e:
            tb7tdjs6nyofj2eisd1p8m3u6q89icsd:
                args:
                    - --epochs
                    - "2"
                    - --batch-size
                    - "4"
                codePath: scripts/production_training.py
                codePathLocal: scripts/production_training.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "311993479168"
                        used: "178745696256"
                email: wer.inc.jp@gmail.com
                executable: /usr/bin/python
                git:
                    commit: efdf5513758bec4a40ff4bb5a680175e89be5b52
                    remote: https://github.com/wer-inc/gogooku3.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6fa85c20-8593-3729-ad6e-4155943a1707
                host: client-instance-au9hc2cl
                memory:
                    total: "232209719296"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.35
                program: /home/ubuntu/gogooku3-standalone/scripts/production_training.py
                python: CPython 3.10.12
                root: /home/ubuntu/gogooku3-standalone
                startedAt: "2025-08-30T00:11:14.132790Z"
                writerId: tb7tdjs6nyofj2eisd1p8m3u6q89icsd
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 103
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.12
            "5": 0.21.2
            "6": 4.54.1
            "12": 0.21.2
            "13": linux-x86_64
batch_size:
    value: 4
cuda_available:
    value: true
data_path:
    value: output/ml_dataset_20250827_174908.parquet
device:
    value: cuda
ema_decay:
    value: 0.995
freq_dropout_p:
    value: 0.2
gat_temperature:
    value: 0.8
huber_delta:
    value: 0.01
learning_rate:
    value: 5e-05
max_epochs:
    value: 2
pytorch_version:
    value: 2.7.1+cu126
scheduler_gamma:
    value: 0.98
warmup_steps:
    value: 1500
