"""DuckDB schema definitions."""

from __future__ import annotations

from collections.abc import Iterable

LISTED_INFO_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("available_ts", "TIMESTAMP WITH TIME ZONE"),
    ("code", "VARCHAR"),
    ("company_name", "VARCHAR"),
    ("company_name_english", "VARCHAR"),
    ("sector17_code", "VARCHAR"),
    ("sector33_code", "VARCHAR"),
    ("sector17_name", "VARCHAR"),
    ("sector33_name", "VARCHAR"),
    ("scale_category", "VARCHAR"),
    ("scale_category_name", "VARCHAR"),
    ("market_code", "VARCHAR"),
    ("market_code_name", "VARCHAR"),
    ("margin_code", "VARCHAR"),
    ("margin_code_name", "VARCHAR"),
]
LISTED_INFO_PK = "PRIMARY KEY (date, code)"

TRADING_CALENDAR_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("holiday_division", "VARCHAR"),
]
TRADING_CALENDAR_PK = "PRIMARY KEY (date)"

DAILY_QUOTES_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("code", "VARCHAR"),
    ("open", "DOUBLE"),
    ("high", "DOUBLE"),
    ("low", "DOUBLE"),
    ("close", "DOUBLE"),
    ("upper_limit", "VARCHAR"),
    ("lower_limit", "VARCHAR"),
    ("volume", "BIGINT"),
    ("turnover_value", "DOUBLE"),
    ("adjustment_factor", "DOUBLE"),
    ("adjustment_open", "DOUBLE"),
    ("adjustment_high", "DOUBLE"),
    ("adjustment_low", "DOUBLE"),
    ("adjustment_close", "DOUBLE"),
    ("adjustment_volume", "BIGINT"),
    ("morning_open", "DOUBLE"),
    ("morning_high", "DOUBLE"),
    ("morning_low", "DOUBLE"),
    ("morning_close", "DOUBLE"),
    ("morning_upper_limit", "VARCHAR"),
    ("morning_lower_limit", "VARCHAR"),
    ("morning_volume", "BIGINT"),
    ("morning_turnover_value", "DOUBLE"),
    ("morning_adjustment_open", "DOUBLE"),
    ("morning_adjustment_high", "DOUBLE"),
    ("morning_adjustment_low", "DOUBLE"),
    ("morning_adjustment_close", "DOUBLE"),
    ("morning_adjustment_volume", "BIGINT"),
    ("afternoon_open", "DOUBLE"),
    ("afternoon_high", "DOUBLE"),
    ("afternoon_low", "DOUBLE"),
    ("afternoon_close", "DOUBLE"),
    ("afternoon_upper_limit", "VARCHAR"),
    ("afternoon_lower_limit", "VARCHAR"),
    ("afternoon_volume", "BIGINT"),
    ("afternoon_turnover_value", "DOUBLE"),
    ("afternoon_adjustment_open", "DOUBLE"),
    ("afternoon_adjustment_high", "DOUBLE"),
    ("afternoon_adjustment_low", "DOUBLE"),
    ("afternoon_adjustment_close", "DOUBLE"),
    ("afternoon_adjustment_volume", "BIGINT"),
]
DAILY_QUOTES_PK = "PRIMARY KEY (date, code)"

BREAKDOWN_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("code", "VARCHAR"),
    ("long_sell_value", "DOUBLE"),
    ("short_sell_without_margin_value", "DOUBLE"),
    ("margin_sell_new_value", "DOUBLE"),
    ("margin_sell_close_value", "DOUBLE"),
    ("long_buy_value", "DOUBLE"),
    ("margin_buy_new_value", "DOUBLE"),
    ("margin_buy_close_value", "DOUBLE"),
    ("long_sell_volume", "BIGINT"),
    ("short_sell_without_margin_volume", "BIGINT"),
    ("margin_sell_new_volume", "BIGINT"),
    ("margin_sell_close_volume", "BIGINT"),
    ("long_buy_volume", "BIGINT"),
    ("margin_buy_new_volume", "BIGINT"),
    ("margin_buy_close_volume", "BIGINT"),
]
BREAKDOWN_PK = "PRIMARY KEY (date, code)"

PRICE_FLOW_FEATURES_TABLE = "price_flow_features"
LISTED_META_FEATURES_TABLE = "listed_meta_features"
FINANCIAL_FEATURES_TABLE = "financial_features"
SECTION_FLOW_FEATURES_TABLE = "section_flow_features"
STATEMENTS_TABLE = "statements"
FS_DETAILS_TABLE = "fs_details"
STATEMENTS_COLUMNS: list[tuple[str, str]] = [
    ("disclosed_date", "DATE"),
    ("disclosed_time", "VARCHAR"),
    ("local_code", "VARCHAR"),
    ("disclosure_number", "VARCHAR"),
    ("type_of_document", "VARCHAR"),
    ("type_of_current_period", "VARCHAR"),
    ("current_period_start_date", "DATE"),
    ("current_period_end_date", "DATE"),
    ("current_fiscal_year_start_date", "DATE"),
    ("current_fiscal_year_end_date", "DATE"),
    ("next_fiscal_year_start_date", "DATE"),
    ("next_fiscal_year_end_date", "DATE"),
    ("net_sales", "VARCHAR"),
    ("operating_profit", "VARCHAR"),
    ("ordinary_profit", "VARCHAR"),
    ("profit", "VARCHAR"),
    ("earnings_per_share", "VARCHAR"),
    ("diluted_earnings_per_share", "VARCHAR"),
    ("total_assets", "VARCHAR"),
    ("equity", "VARCHAR"),
    ("equity_to_asset_ratio", "VARCHAR"),
    ("book_value_per_share", "VARCHAR"),
    ("cash_flows_from_operating_activities", "VARCHAR"),
    ("cash_flows_from_investing_activities", "VARCHAR"),
    ("cash_flows_from_financing_activities", "VARCHAR"),
    ("cash_and_equivalents", "VARCHAR"),
    ("result_dividend_per_share_1st_quarter", "VARCHAR"),
    ("result_dividend_per_share_2nd_quarter", "VARCHAR"),
    ("result_dividend_per_share_3rd_quarter", "VARCHAR"),
    ("result_dividend_per_share_fiscal_year_end", "VARCHAR"),
    ("result_dividend_per_share_annual", "VARCHAR"),
    ("distributions_per_unit_reit", "VARCHAR"),
    ("result_total_dividend_paid_annual", "VARCHAR"),
    ("result_payout_ratio_annual", "VARCHAR"),
    ("forecast_dividend_per_share_1st_quarter", "VARCHAR"),
    ("forecast_dividend_per_share_2nd_quarter", "VARCHAR"),
    ("forecast_dividend_per_share_3rd_quarter", "VARCHAR"),
    ("forecast_dividend_per_share_fiscal_year_end", "VARCHAR"),
    ("forecast_dividend_per_share_annual", "VARCHAR"),
    ("forecast_distributions_per_unit_reit", "VARCHAR"),
    ("forecast_total_dividend_paid_annual", "VARCHAR"),
    ("forecast_payout_ratio_annual", "VARCHAR"),
    ("next_year_forecast_dividend_per_share_1st_quarter", "VARCHAR"),
    ("next_year_forecast_dividend_per_share_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_dividend_per_share_3rd_quarter", "VARCHAR"),
    ("next_year_forecast_dividend_per_share_fiscal_year_end", "VARCHAR"),
    ("next_year_forecast_dividend_per_share_annual", "VARCHAR"),
    ("next_year_forecast_distributions_per_unit_reit", "VARCHAR"),
    ("next_year_forecast_payout_ratio_annual", "VARCHAR"),
    ("forecast_net_sales_2nd_quarter", "VARCHAR"),
    ("forecast_operating_profit_2nd_quarter", "VARCHAR"),
    ("forecast_ordinary_profit_2nd_quarter", "VARCHAR"),
    ("forecast_profit_2nd_quarter", "VARCHAR"),
    ("forecast_earnings_per_share_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_net_sales_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_operating_profit_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_ordinary_profit_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_profit_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_earnings_per_share_2nd_quarter", "VARCHAR"),
    ("forecast_net_sales", "VARCHAR"),
    ("forecast_operating_profit", "VARCHAR"),
    ("forecast_ordinary_profit", "VARCHAR"),
    ("forecast_profit", "VARCHAR"),
    ("forecast_earnings_per_share", "VARCHAR"),
    ("next_year_forecast_net_sales", "VARCHAR"),
    ("next_year_forecast_operating_profit", "VARCHAR"),
    ("next_year_forecast_ordinary_profit", "VARCHAR"),
    ("next_year_forecast_profit", "VARCHAR"),
    ("next_year_forecast_earnings_per_share", "VARCHAR"),
    ("material_changes_in_subsidiaries", "VARCHAR"),
    ("significant_changes_in_the_scope_of_consolidation", "VARCHAR"),
    ("changes_based_on_revisions_of_accounting_standard", "VARCHAR"),
    ("changes_other_than_ones_based_on_revisions_of_accounting_standard", "VARCHAR"),
    ("changes_in_accounting_estimates", "VARCHAR"),
    ("retrospective_restatement", "VARCHAR"),
    ("number_of_issued_and_outstanding_shares_at_the_end_of_fiscal_year_including_treasury_stock", "VARCHAR"),
    ("number_of_treasury_stock_at_the_end_of_fiscal_year", "VARCHAR"),
    ("average_number_of_shares", "VARCHAR"),
    ("non_consolidated_net_sales", "VARCHAR"),
    ("non_consolidated_operating_profit", "VARCHAR"),
    ("non_consolidated_ordinary_profit", "VARCHAR"),
    ("non_consolidated_profit", "VARCHAR"),
    ("non_consolidated_earnings_per_share", "VARCHAR"),
    ("non_consolidated_total_assets", "VARCHAR"),
    ("non_consolidated_equity", "VARCHAR"),
    ("non_consolidated_equity_to_asset_ratio", "VARCHAR"),
    ("non_consolidated_book_value_per_share", "VARCHAR"),
    ("forecast_non_consolidated_net_sales_2nd_quarter", "VARCHAR"),
    ("forecast_non_consolidated_operating_profit_2nd_quarter", "VARCHAR"),
    ("forecast_non_consolidated_ordinary_profit_2nd_quarter", "VARCHAR"),
    ("forecast_non_consolidated_profit_2nd_quarter", "VARCHAR"),
    ("forecast_non_consolidated_earnings_per_share_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_non_consolidated_net_sales_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_non_consolidated_operating_profit_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_non_consolidated_ordinary_profit_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_non_consolidated_profit_2nd_quarter", "VARCHAR"),
    ("next_year_forecast_non_consolidated_earnings_per_share_2nd_quarter", "VARCHAR"),
    ("forecast_non_consolidated_net_sales", "VARCHAR"),
    ("forecast_non_consolidated_operating_profit", "VARCHAR"),
    ("forecast_non_consolidated_ordinary_profit", "VARCHAR"),
    ("forecast_non_consolidated_profit", "VARCHAR"),
    ("forecast_non_consolidated_earnings_per_share", "VARCHAR"),
    ("next_year_forecast_non_consolidated_net_sales", "VARCHAR"),
    ("next_year_forecast_non_consolidated_operating_profit", "VARCHAR"),
    ("next_year_forecast_non_consolidated_ordinary_profit", "VARCHAR"),
    ("next_year_forecast_non_consolidated_profit", "VARCHAR"),
    ("next_year_forecast_non_consolidated_earnings_per_share", "VARCHAR"),
]
STATEMENTS_PK = "PRIMARY KEY (disclosed_date, local_code, disclosure_number)"

FS_DETAILS_COLUMNS: list[tuple[str, str]] = [
    ("disclosed_date", "DATE"),
    ("disclosed_time", "VARCHAR"),
    ("local_code", "VARCHAR"),
    ("disclosure_number", "VARCHAR"),
    ("type_of_document", "VARCHAR"),
    # FinancialStatement is stored as JSON string to preserve arbitrary keys.
    ("financial_statement_json", "VARCHAR"),
]
FS_DETAILS_PK = "PRIMARY KEY (disclosed_date, local_code, disclosure_number)"

TRADES_SPEC_COLUMNS: list[tuple[str, str]] = [
    ("published_date", "DATE"),
    ("start_date", "DATE"),
    ("end_date", "DATE"),
    ("section", "VARCHAR"),
    ("proprietary_sales", "DOUBLE"),
    ("proprietary_purchases", "DOUBLE"),
    ("proprietary_total", "DOUBLE"),
    ("proprietary_balance", "DOUBLE"),
    ("brokerage_sales", "DOUBLE"),
    ("brokerage_purchases", "DOUBLE"),
    ("brokerage_total", "DOUBLE"),
    ("brokerage_balance", "DOUBLE"),
    ("total_sales", "DOUBLE"),
    ("total_purchases", "DOUBLE"),
    ("total_total", "DOUBLE"),
    ("total_balance", "DOUBLE"),
    ("individuals_sales", "DOUBLE"),
    ("individuals_purchases", "DOUBLE"),
    ("individuals_total", "DOUBLE"),
    ("individuals_balance", "DOUBLE"),
    ("foreigners_sales", "DOUBLE"),
    ("foreigners_purchases", "DOUBLE"),
    ("foreigners_total", "DOUBLE"),
    ("foreigners_balance", "DOUBLE"),
    ("securities_cos_sales", "DOUBLE"),
    ("securities_cos_purchases", "DOUBLE"),
    ("securities_cos_total", "DOUBLE"),
    ("securities_cos_balance", "DOUBLE"),
    ("investment_trusts_sales", "DOUBLE"),
    ("investment_trusts_purchases", "DOUBLE"),
    ("investment_trusts_total", "DOUBLE"),
    ("investment_trusts_balance", "DOUBLE"),
    ("business_cos_sales", "DOUBLE"),
    ("business_cos_purchases", "DOUBLE"),
    ("business_cos_total", "DOUBLE"),
    ("business_cos_balance", "DOUBLE"),
    ("other_cos_sales", "DOUBLE"),
    ("other_cos_purchases", "DOUBLE"),
    ("other_cos_total", "DOUBLE"),
    ("other_cos_balance", "DOUBLE"),
    ("insurance_cos_sales", "DOUBLE"),
    ("insurance_cos_purchases", "DOUBLE"),
    ("insurance_cos_total", "DOUBLE"),
    ("insurance_cos_balance", "DOUBLE"),
    ("city_bks_regional_bks_etc_sales", "DOUBLE"),
    ("city_bks_regional_bks_etc_purchases", "DOUBLE"),
    ("city_bks_regional_bks_etc_total", "DOUBLE"),
    ("city_bks_regional_bks_etc_balance", "DOUBLE"),
    ("trust_banks_sales", "DOUBLE"),
    ("trust_banks_purchases", "DOUBLE"),
    ("trust_banks_total", "DOUBLE"),
    ("trust_banks_balance", "DOUBLE"),
    ("other_financial_institutions_sales", "DOUBLE"),
    ("other_financial_institutions_purchases", "DOUBLE"),
    ("other_financial_institutions_total", "DOUBLE"),
    ("other_financial_institutions_balance", "DOUBLE"),
]
TRADES_SPEC_PK = "PRIMARY KEY (published_date, section, start_date, end_date)"

WEEKLY_MARGIN_INTEREST_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("code", "VARCHAR"),
    ("short_margin_trade_volume", "DOUBLE"),
    ("long_margin_trade_volume", "DOUBLE"),
    ("short_negotiable_margin_trade_volume", "DOUBLE"),
    ("long_negotiable_margin_trade_volume", "DOUBLE"),
    ("short_standardized_margin_trade_volume", "DOUBLE"),
    ("long_standardized_margin_trade_volume", "DOUBLE"),
    ("issue_type", "VARCHAR"),
]
WEEKLY_MARGIN_INTEREST_PK = "PRIMARY KEY (date, code)"

SHORT_SELLING_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("sector33_code", "VARCHAR"),
    ("selling_excluding_short_selling_turnover_value", "DOUBLE"),
    ("short_selling_with_restrictions_turnover_value", "DOUBLE"),
    ("short_selling_without_restrictions_turnover_value", "DOUBLE"),
]
SHORT_SELLING_PK = "PRIMARY KEY (date, sector33_code)"

SHORT_SELLING_POSITIONS_COLUMNS: list[tuple[str, str]] = [
    ("disclosed_date", "DATE"),
    ("calculated_date", "DATE"),
    ("code", "VARCHAR"),
    ("short_seller_name", "VARCHAR"),
    ("short_seller_address", "VARCHAR"),
    ("discretionary_investment_contractor_name", "VARCHAR"),
    ("discretionary_investment_contractor_address", "VARCHAR"),
    ("investment_fund_name", "VARCHAR"),
    ("short_positions_to_shares_outstanding_ratio", "DOUBLE"),
    ("short_positions_in_shares_number", "DOUBLE"),
    ("short_positions_in_trading_units_number", "DOUBLE"),
    ("calculation_in_previous_reporting_date", "DATE"),
    ("short_positions_in_previous_reporting_ratio", "DOUBLE"),
    ("notes", "VARCHAR"),
]
SHORT_SELLING_POSITIONS_PK = "PRIMARY KEY (disclosed_date, code, short_seller_name, calculated_date)"

SECTION_FLOW_FEATURES_COLUMNS: list[tuple[str, str]] = [
    ("published_date", "DATE"),
    ("effective_date", "DATE"),
    ("start_date", "DATE"),
    ("end_date", "DATE"),
    ("section", "VARCHAR"),
    # base net/ratio
    ("foreigners_net", "DOUBLE"),
    ("individuals_net", "DOUBLE"),
    ("trust_banks_net", "DOUBLE"),
    ("investment_trusts_net", "DOUBLE"),
    ("total_turnover", "DOUBLE"),
    ("foreigners_net_ratio", "DOUBLE"),
    ("individuals_net_ratio", "DOUBLE"),
    ("trust_banks_net_ratio", "DOUBLE"),
    ("smart_net_ratio", "DOUBLE"),
    ("retail_net_ratio", "DOUBLE"),
    ("smart_vs_retail", "DOUBLE"),
    # rolling sums
    ("foreigners_net_cum_4w", "DOUBLE"),
    ("foreigners_net_cum_13w", "DOUBLE"),
    ("smart_vs_retail_cum_4w", "DOUBLE"),
    ("smart_vs_retail_cum_13w", "DOUBLE"),
    ("foreigners_net_ratio_cum_4w", "DOUBLE"),
    ("foreigners_net_ratio_cum_13w", "DOUBLE"),
    ("individuals_net_ratio_cum_4w", "DOUBLE"),
    ("individuals_net_ratio_cum_13w", "DOUBLE"),
    ("foreigners_net_ratio_trend_4w", "DOUBLE"),
    ("individuals_net_ratio_trend_4w", "DOUBLE"),
    ("smart_vs_retail_trend_4w", "DOUBLE"),
    # z-scores
    ("foreigners_net_ratio_z_26w", "DOUBLE"),
    ("individuals_net_ratio_z_26w", "DOUBLE"),
    ("smart_vs_retail_z_26w", "DOUBLE"),
    # streaks
    ("foreigners_buy_streak", "INT"),
    ("foreigners_sell_streak", "INT"),
    ("individuals_buy_streak", "INT"),
    ("individuals_sell_streak", "INT"),
]
SECTION_FLOW_FEATURES_PK = "PRIMARY KEY (published_date, section)"

FINANCIAL_FEATURES_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("code", "VARCHAR"),
    # Snapshot-level fundamentals carried to daily (latest as of each date)
    ("fin_sales_ttm", "DOUBLE"),
    ("fin_op_profit_ttm", "DOUBLE"),
    ("fin_profit_ttm", "DOUBLE"),
    ("fin_eps_ttm", "DOUBLE"),
    ("fin_profit_margin", "DOUBLE"),
    ("fin_roe", "DOUBLE"),
    ("fin_roa", "DOUBLE"),
    ("fin_cfo_ttm", "DOUBLE"),
    ("fin_cfo_to_ni", "DOUBLE"),
    ("fin_equity_ratio", "DOUBLE"),
    # Daily-level valuation / balance-sheet ratios
    ("fin_shares_outstanding_fs", "DOUBLE"),
    ("fin_pe", "DOUBLE"),
    ("fin_net_cash_ratio", "DOUBLE"),
    ("fin_net_cash_per_share", "DOUBLE"),
    ("fin_cash_neutral_pe", "DOUBLE"),
    # K1-style fundamentals (net cash, valuation, growth, quality)
    ("fund_net_cash_k1", "DOUBLE"),
    ("fund_k1_components_missing", "BOOLEAN"),
    ("fund_net_cash_ratio_k1", "DOUBLE"),
    ("fund_net_cash_ratio_k1_clipped", "DOUBLE"),
    ("fund_net_cash_ratio_k1_log", "DOUBLE"),
    ("fund_net_cash_per_share", "DOUBLE"),
    ("fund_per_ttm", "DOUBLE"),
    ("fund_pbr", "DOUBLE"),
    ("fund_cash_neutral_per", "DOUBLE"),
    ("fund_yoy_sales", "DOUBLE"),
    ("fund_yoy_profit", "DOUBLE"),
    ("fund_yoy_cfo", "DOUBLE"),
    ("fund_yoy_net_cash", "DOUBLE"),
    ("fund_roe", "DOUBLE"),
    ("fund_op_margin", "DOUBLE"),
    ("fund_accruals", "DOUBLE"),
    ("fund_is_cash_rich", "INT"),
    ("fund_is_high_net_cash", "INT"),
    ("fund_value_trap_flag", "INT"),
    ("earn_sales_surprise_fy", "DOUBLE"),
    ("earn_op_profit_surprise_fy", "DOUBLE"),
    ("earn_profit_surprise_fy", "DOUBLE"),
    ("earn_eps_surprise_fy", "DOUBLE"),
    ("earn_sales_revision_fy", "DOUBLE"),
    ("earn_op_profit_revision_fy", "DOUBLE"),
    ("earn_profit_revision_fy", "DOUBLE"),
    ("earn_eps_revision_fy", "DOUBLE"),
    ("earn_sales_revision_cum_fy", "DOUBLE"),
    ("earn_op_profit_revision_cum_fy", "DOUBLE"),
    ("earn_profit_revision_cum_fy", "DOUBLE"),
    ("earn_eps_revision_cum_fy", "DOUBLE"),
    ("earn_sales_next_fy_growth", "DOUBLE"),
    ("earn_op_profit_next_fy_growth", "DOUBLE"),
    ("earn_profit_next_fy_growth", "DOUBLE"),
    ("earn_eps_next_fy_growth", "DOUBLE"),
]
FINANCIAL_FEATURES_PK = "PRIMARY KEY (date, code)"

# Core feature schema (price + flow + listed meta) used for price_flow_features
FEATURES_DAILY_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("code", "VARCHAR"),
    ("ret_1d", "DOUBLE"),
    ("has_price_core", "INT"),
    ("ret_5d", "DOUBLE"),
    ("ret_20d", "DOUBLE"),
    ("ret_60d", "DOUBLE"),
    ("has_long_window_60", "INT"),
    ("mom_accel", "DOUBLE"),
    ("logret_1d", "DOUBLE"),
    ("ret_intraday", "DOUBLE"),
    ("ret_overnight", "DOUBLE"),
    ("mom_5", "DOUBLE"),
    ("mom_10", "DOUBLE"),
    ("mom_20", "DOUBLE"),
    ("mom_chg_5_20", "DOUBLE"),
    ("fwd_ret_1d", "DOUBLE"),
    ("fwd_ret_5d", "DOUBLE"),
    ("fwd_ret_10d", "DOUBLE"),
    ("fwd_ret_20d", "DOUBLE"),
    ("has_target_1d", "INT"),
    ("has_target_5d", "INT"),
    ("has_target_10d", "INT"),
    ("has_target_20d", "INT"),
    # Listed info / sector meta
    ("sector17_code", "VARCHAR"),
    ("sector33_code", "VARCHAR"),
    ("market_code", "VARCHAR"),
    ("scale_category", "VARCHAR"),
    ("margin_code", "VARCHAR"),
    ("is_prime", "INT"),
    ("is_standard", "INT"),
    ("is_growth", "INT"),
    ("is_margin_eligible", "INT"),
    ("is_shortable", "INT"),
    ("has_sector_meta", "INT"),
    # Scale category booleans
    ("is_small_cap", "INT"),
    ("is_mid_cap", "INT"),
    ("is_large_cap", "INT"),
    # Sector returns (equal-weight mean per date x sector33)
    ("sector_ret_1d", "DOUBLE"),
    ("sector_ret_5d", "DOUBLE"),
    ("sector_ret_20d", "DOUBLE"),
    # Sector-neutral alpha (stock return - sector mean)
    ("sector_alpha_ret_1d", "DOUBLE"),
    ("sector_alpha_ret_5d", "DOUBLE"),
    ("sector_alpha_ret_20d", "DOUBLE"),
    # Sector-within percentile rank (0-1) and rank (5d)
    ("sector_pct_ret_1d", "DOUBLE"),
    ("sector_pct_ret_5d", "DOUBLE"),
    ("sector_pct_ret_20d", "DOUBLE"),
    ("sector_rank_ret_5d", "DOUBLE"),
    # === end of listed meta block ===
    ("rv_5", "DOUBLE"),
    ("rv_20", "DOUBLE"),
    ("rv_ratio", "DOUBLE"),
    ("rv_z_20", "DOUBLE"),
    ("vol_20d", "DOUBLE"),
    ("range", "DOUBLE"),
    ("range_z_20", "DOUBLE"),
    ("parkinson_20", "DOUBLE"),
    ("gk_20", "DOUBLE"),
    # Phase 3.1: Risk/Drawdown features
    ("drawdown_from_high_20", "DOUBLE"),
    ("drawdown_from_high_60", "DOUBLE"),
    ("max_drawdown_20", "DOUBLE"),
    ("max_drawdown_60", "DOUBLE"),
    ("risk_adj_mom_20", "DOUBLE"),
    ("risk_adj_mom_5", "DOUBLE"),
    ("underwater_days_20", "INT"),
    ("recovery_rate_20", "DOUBLE"),
    # end Phase 3.1
    # Phase 3.2: Market Alpha features
    ("market_alpha_1d", "DOUBLE"),
    ("market_alpha_5d", "DOUBLE"),
    ("market_alpha_20d", "DOUBLE"),
    ("rel_strength_5d", "DOUBLE"),
    ("rel_strength_20d", "DOUBLE"),
    ("cum_alpha_20d", "DOUBLE"),
    ("info_ratio_20d", "DOUBLE"),
    # end Phase 3.2
    # Phase 3.3: Volatility Regime features
    ("vol_expansion", "INT"),
    ("vol_trend_20", "DOUBLE"),
    ("vol_regime", "INT"),
    ("cs_vol_percentile", "DOUBLE"),
    ("vol_weighted_mom_20", "DOUBLE"),
    # end Phase 3.3
    ("vol_ratio_5", "DOUBLE"),
    ("vol_ratio_20", "DOUBLE"),
    ("vol_ratio_5_20", "DOUBLE"),
    ("vol_z_20", "DOUBLE"),
    ("val_ratio_5", "DOUBLE"),
    ("val_ratio_20", "DOUBLE"),
    ("val_z_20", "DOUBLE"),
    ("price_pos_20", "DOUBLE"),
    ("dist_from_high52", "DOUBLE"),
    ("dist_from_low52", "DOUBLE"),
    ("price_dev_5", "DOUBLE"),
    ("price_dev_20", "DOUBLE"),
    ("dev_ma60", "DOUBLE"),
    ("amihud_1d", "DOUBLE"),
    ("amihud_20", "DOUBLE"),
    ("log_amihud_1d", "DOUBLE"),
    ("log_amihud_20", "DOUBLE"),
    ("vwap", "DOUBLE"),
    ("gap_abs", "DOUBLE"),
    ("gap_dir", "DOUBLE"),
    ("dollar_volume", "DOUBLE"),
    ("breakdown_buy_ratio", "DOUBLE"),
    ("breakdown_sell_ratio", "DOUBLE"),
    ("breakdown_volume_ratio", "DOUBLE"),
    ("has_breakdown", "INT"),
    ("limit_volume_ratio", "DOUBLE"),
    ("overnight_gap", "DOUBLE"),
    ("lunch_gap", "DOUBLE"),
    ("ret_morning", "DOUBLE"),
    ("ret_afternoon", "DOUBLE"),
    ("session_divergence", "DOUBLE"),
    ("morning_vol_share", "DOUBLE"),
    ("afternoon_vol_share", "DOUBLE"),
    ("has_sessions", "INT"),
    ("session_volume_ratio", "DOUBLE"),
    ("morning_trend_eff", "DOUBLE"),
    ("afternoon_trend_eff", "DOUBLE"),
    ("rsi_14", "DOUBLE"),
    ("bb_mid_20_2", "DOUBLE"),
    ("bb_upper_20_2", "DOUBLE"),
    ("bb_lower_20_2", "DOUBLE"),
    ("bb_percent_b_20_2", "DOUBLE"),
    ("bb_width_20_2", "DOUBLE"),
    ("atr_14", "DOUBLE"),
    ("is_limit_up", "INT"),
    ("is_limit_down", "INT"),
    ("limit_up_count_20", "INT"),
    ("limit_down_count_20", "INT"),
    ("days_since_limit_up", "INT"),
    ("days_since_limit_down", "INT"),
    ("is_split", "INT"),
    # Breakdown-derived demand features
    ("sell_long_ratio", "DOUBLE"),
    ("sell_short_ratio", "DOUBLE"),
    ("sell_margin_close_ratio", "DOUBLE"),
    ("buy_long_ratio", "DOUBLE"),
    ("buy_margin_new_ratio", "DOUBLE"),
    ("buy_margin_close_ratio", "DOUBLE"),
    ("credit_buy_share", "DOUBLE"),
    ("credit_sell_share", "DOUBLE"),
    ("credit_turnover_share", "DOUBLE"),
    ("net_flow_value", "DOUBLE"),
    ("flow_imbalance", "DOUBLE"),
    ("net_long_value", "DOUBLE"),
    ("net_long_ratio", "DOUBLE"),
    ("net_margin_new_value", "DOUBLE"),
    ("margin_new_sentiment", "DOUBLE"),
    ("bull_bear_ratio", "DOUBLE"),
    ("inst_short_ratio_value", "DOUBLE"),
    ("retail_lev_ratio_value", "DOUBLE"),
    ("margin_capitulation_ratio", "DOUBLE"),
    ("margin_capitulation_ma5", "DOUBLE"),
    ("margin_capitulation_spike", "DOUBLE"),
    ("net_margin_flow_value", "DOUBLE"),
    ("margin_flow_intensity", "DOUBLE"),
    ("short_ratio_ma_5", "DOUBLE"),
    ("short_ratio_ma_20", "DOUBLE"),
    ("short_ratio_dev_5", "DOUBLE"),
    ("short_ratio_dev_20", "DOUBLE"),
    ("short_ratio_chg_1", "DOUBLE"),
    ("short_ratio_chg_5", "DOUBLE"),
    ("long_buy_ratio_ma_5", "DOUBLE"),
    ("long_buy_ratio_ma_20", "DOUBLE"),
    ("long_buy_ratio_dev_5", "DOUBLE"),
    ("long_buy_ratio_dev_20", "DOUBLE"),
    ("long_buy_ratio_chg_1", "DOUBLE"),
    ("long_buy_ratio_chg_5", "DOUBLE"),
    ("short_ratio_z_60", "DOUBLE"),
    ("long_buy_ratio_z_60", "DOUBLE"),
    ("flow_imbalance_z_60", "DOUBLE"),
    ("delta_margin_long_vol", "DOUBLE"),
    ("delta_margin_short_vol", "DOUBLE"),
    ("cum_margin_long_60", "DOUBLE"),
    ("cum_margin_short_60", "DOUBLE"),
    ("adv_vol_20", "DOUBLE"),
    ("short_overhang_days", "DOUBLE"),
    ("long_overhang_days", "DOUBLE"),
    ("short_squeeze_risk", "DOUBLE"),
    ("long_liquidation_risk", "DOUBLE"),
    ("cs_pct_sell_short_ratio", "DOUBLE"),
    ("cs_pct_flow_imbalance", "DOUBLE"),
    ("cs_pct_short_overhang_days", "DOUBLE"),
    ("cs_pct_credit_turnover_share", "DOUBLE"),
    ("cs_z_short_ratio", "DOUBLE"),
    ("cs_z_flow_imbalance", "DOUBLE"),
    ("flow_price_alignment", "DOUBLE"),
    ("short_price_alignment", "DOUBLE"),
    ("flow_intensity", "DOUBLE"),
    ("short_intensity", "DOUBLE"),
    ("flow_vol_combo", "DOUBLE"),
    ("flow_vol_ratio", "DOUBLE"),
    ("sector_short_ratio", "DOUBLE"),
    ("sector_short_trend", "DOUBLE"),
    # Additional prices/breakdown technicals and patterns
    ("ema_12", "DOUBLE"),
    ("ema_26", "DOUBLE"),
    ("macd", "DOUBLE"),
    ("macd_signal", "DOUBLE"),
    ("macd_hist", "DOUBLE"),
    ("macd_hist_diff_1", "DOUBLE"),
    ("adx_14", "DOUBLE"),
    ("adx_slope_5", "DOUBLE"),
    ("cand_body", "DOUBLE"),
    ("cand_body_ratio", "DOUBLE"),
    ("cand_upper_shadow", "DOUBLE"),
    ("cand_lower_shadow", "DOUBLE"),
    ("cand_is_bull", "INT"),
    ("bull_run_len", "INT"),
    ("bear_run_len", "INT"),
    ("bull_ratio_5d", "DOUBLE"),
    ("bull_ratio_20d", "DOUBLE"),
    ("range_morning", "DOUBLE"),
    ("range_afternoon", "DOUBLE"),
    ("session_vol_ratio", "DOUBLE"),
    ("morning_win_rate_20", "DOUBLE"),
    ("afternoon_win_rate_20", "DOUBLE"),
    ("session_corr_20", "DOUBLE"),
    ("cs_pct_ret_1d", "DOUBLE"),
    ("cs_pct_dollar_volume", "DOUBLE"),
    ("cs_z_ret_1d", "DOUBLE"),
    ("cs_z_vol_z_20", "DOUBLE"),
    ("cs_rank_ret_1d", "DOUBLE"),
    ("cs_rank_ret_5d", "DOUBLE"),
    ("cs_rank_short_ratio", "DOUBLE"),
    # Volume-based breakdown ratios
    ("sell_short_ratio_vol", "DOUBLE"),
    ("buy_margin_new_ratio_vol", "DOUBLE"),
    ("buy_margin_close_ratio_vol", "DOUBLE"),
    ("sell_margin_close_ratio_vol", "DOUBLE"),
    # Flow run lengths
    ("pos_flow_run_len", "INT"),
    ("neg_flow_run_len", "INT"),
    # Short selling positions (event-driven) projected to daily
    ("ssp_disclosed_short_ratio", "DOUBLE"),
    ("ssp_short_disclosure_flag_recent", "INT"),
]
FEATURES_DAILY_PK = "PRIMARY KEY (date, code)"

# Listed meta-only table schema (separate from price_flow_features)
LISTED_META_FEATURES_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("code", "VARCHAR"),
    ("sector17_code", "VARCHAR"),
    ("sector33_code", "VARCHAR"),
    ("market_code", "VARCHAR"),
    ("scale_category", "VARCHAR"),
    ("margin_code", "VARCHAR"),
    ("is_prime", "INT"),
    ("is_standard", "INT"),
    ("is_growth", "INT"),
    ("is_margin_eligible", "INT"),
    ("is_shortable", "INT"),
    ("has_sector_meta", "INT"),
    ("is_small_cap", "INT"),
    ("is_mid_cap", "INT"),
    ("is_large_cap", "INT"),
    ("sector_ret_1d", "DOUBLE"),
    ("sector_ret_5d", "DOUBLE"),
    ("sector_ret_20d", "DOUBLE"),
    ("sector_alpha_ret_1d", "DOUBLE"),
    ("sector_alpha_ret_5d", "DOUBLE"),
    ("sector_alpha_ret_20d", "DOUBLE"),
    ("sector_pct_ret_1d", "DOUBLE"),
    ("sector_pct_ret_5d", "DOUBLE"),
    ("sector_pct_ret_20d", "DOUBLE"),
    ("sector_rank_ret_5d", "DOUBLE"),
]
LISTED_META_FEATURES_PK = "PRIMARY KEY (date, code)"

YF_PRICE_COLUMNS: list[tuple[str, str]] = [
    ("date", "DATE"),
    ("ticker", "VARCHAR"),
    ("open", "DOUBLE"),
    ("high", "DOUBLE"),
    ("low", "DOUBLE"),
    ("close", "DOUBLE"),
    ("adj_close", "DOUBLE"),
    ("volume", "BIGINT"),
]
YF_PRICE_PK = "PRIMARY KEY (date, ticker)"


def create_table_sql(name: str, columns: Iterable[tuple[str, str]], constraint: str | None = None) -> str:
    cols = ",\n    ".join([f"{col} {dtype}" for col, dtype in columns])
    constraint_sql = f", {constraint}" if constraint else ""
    return f"CREATE TABLE IF NOT EXISTS {name} (\n    {cols}{constraint_sql}\n);"
