# @package hydra/hydra_logging

version: 1
formatters:
  simple:
    format: "[%(asctime)s][HYDRA][%(levelname)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
disable_existing_loggers: false

