_wandb:
    value:
        cli_version: 0.21.2
        e:
            id8tulst7l8ewydvvn9m0tjyw9r4uurp:
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "311993479168"
                        used: "178744258560"
                email: wer.inc.jp@gmail.com
                executable: /usr/bin/python
                git:
                    commit: efdf5513758bec4a40ff4bb5a680175e89be5b52
                    remote: https://github.com/wer-inc/gogooku3.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6fa85c20-8593-3729-ad6e-4155943a1707
                host: client-instance-au9hc2cl
                memory:
                    total: "232209719296"
                os: Linux-6.8.0-1030-azure-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.10.12
                root: /home/ubuntu/gogooku3-standalone
                startedAt: "2025-08-30T00:02:16.550071Z"
                writerId: id8tulst7l8ewydvvn9m0tjyw9r4uurp
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.12
            "5": 0.21.2
            "12": 0.21.2
            "13": linux-x86_64
data:
    value:
        graph_builder:
            cache_dir: graph_cache
            ewm_halflife: 20
            k: 15
            log_mktcap_col: log_mktcap
            lookback: 60
            method: ewm_demean
            min_obs: 40
            return_cols:
                - return_1d
                - feat_ret_1d
            sector_col: sector33
            shrinkage_gamma: 0.05
            size_tau: 1
            source_glob: ${data.source.data_dir}/*.parquet
            symmetric: true
debug:
    value:
        detect_anomaly: false
        enabled: false
        fast_dev_run: 10
        profiler: false
defaults:
    value:
        - _self_
        - data: jpx_large_scale
        - model: atft_gat_fan
        - train: production
        - hardware: default
        - override hydra/hydra_logging: default
        - override hydra/job_logging: jst
ema_decay:
    value: 0.995
freq_dropout_p:
    value: 0.2
gat_temperature:
    value: 0.8
hydra:
    value:
        job:
            chdir: false
            name: ATFT-GAT-FAN
        run:
            dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
        sweep:
            dir: logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
            subdir: ${hydra.job.num}
improvements:
    value:
        auto_recover_oom: true
        compile_model: false
        edge_dropout_p: 0
        ema_decay: 0.995
        emergency_checkpoint: false
        enable_tensorboard: true
        enable_wandb: true
        freq_dropout_max_width: 0.2
        freq_dropout_min_width: 0.05
        freq_dropout_p: 0.2
        gat_alpha_min: 0.05
        gat_temperature: 0.8
        huber_delta: 0.01
        huber_loss: true
        log_grad_norm: false
        memory_map: false
        multi_horizon_weights:
            - 1
            - 0.8
            - 0.7
            - 0.5
            - 0.3
        online_normalization: true
        output_head_small_init: true
        use_ema: true
improvements_enabled:
    value: true
logging:
    value:
        level: INFO
mode:
    value: train
model_type:
    value: ATFT-GAT-FAN
paths:
    value:
        data: data
        logs: logs
        models: models
        root: .
project:
    value:
        deterministic: true
        name: ATFT-GAT-FAN
        seed: 42
