defaults:
  - adaptive

# Extend adaptive training with longer fine-tuning phase and tightened stopping
trainer:
  max_epochs: 60

early_stopping:
  patience: 4

phase_training:
  phases:
    augmentation:
      epochs: 15
